### ISSUE TITLE
Rollback suggestion to java 1.8 

### ISSUE THREAD

**Issue by Nihilus13** [securevale/android-rasp#2]
Rollback suggestion to java 1.8 due to incompatibility jave version issues. Some apps are still targeting java 1.8 and need to preserve that compatibility. In RASP project I am not able to see real profit of keeping Java 17. Java 1.8 is still suitable and looks like works the same. I understand that can be issues with plugins or building, but I think it's worth to keep in mind lower version.

**Comment by bmaciejm** [comment]
Hi, thank you for raising this!

Java 8 is very old version and I don't want to rollback to such old one (as this will also require possible downgrade of Gradle Plugin and some other plugins alongside with the IDE used for development). Also the main point of this project is to keep the stack mostly up-to-date to support newest stuff and technologies in Android. 

What I would suggest (and I see you already did it) is to create a fork of this library and do all necessary (downgrading) work on your own. It will require fork maintaining when original library will be updated but it is the best option you have.
I will try to provide help in fixing any cases when future upgrades will brake your fork.

**Comment by Nihilus13** [comment]
Ok, sounds reasonable.
