### ISSUE TITLE
Java project compability

### ISSUE THREAD

**Issue by odemolliens** [securevale/android-rasp#4]
Using *.native.* as a package name is not permitted in Java classes, as "native" is a reserved keyword in Java.
![Screenshot 2024-11-19 at 07 35 57](https://github.com/user-attachments/assets/26b21ea6-a3e3-455a-9137-b60a1e7665b2)

### Workaround:

Intermediate Kotlin File: Create an intermediate file in Kotlin to handle the issue.

![Screenshot 2024-11-19 at 07 36 47](https://github.com/user-attachments/assets/74404917-b70f-4e8b-a96d-26fad63515a4)

Java Integration: Call the intermediate Kotlin file from your Java code.
![Screenshot 2024-11-19 at 07 35 18](https://github.com/user-attachments/assets/da2373cb-de79-4373-8cfa-6dac47ffe9e2)

Recommended Solution:
Please rename the native package to a different name. This should resolve the issue completely.

This problem is linked to [#3](https://github.com/securevale/android-rasp/issues/4#).

**Comment by bmaciejm** [comment]
Thank you for reporting this, I will address it next week.

**Comment by bmaciejm** [comment]
Adressed in https://github.com/securevale/android-rasp/commit/9b646c20c131bbeff5a52ceb29ebd241f7dd9be1.

Will be released as a part of next release `0.7.0`

**Comment by bmaciejm** [comment]
Adressed in https://github.com/securevale/android-rasp/commit/9b646c20c131bbeff5a52ceb29ebd241f7dd9be1.

Will be released as a part of next release `0.7.0`
